### ISSUE TITLE
Cannot casts roles.name field with enums

### ISSUE THREAD

**Issue by kamaludin21** [Althinect/filament-spatie-roles-permissions#186]
When add at Role model:

protected $casts = ['name' => EnumsRole::class];

suddenly 'Super Admin' cannot access everything, but another Role can. 

// Role model
<img width="647" alt="Screenshot 2024-06-19 at 08 38 36" src="https://github.com/Althinect/filament-spatie-roles-permissions/assets/29424767/54ebe1bb-7eeb-475c-abe9-2ee79efccd11">

// Enums class
<img width="647" alt="Screenshot 2024-06-19 at 08 39 01" src="https://github.com/Althinect/filament-spatie-roles-permissions/assets/29424767/46c2a866-8897-41a7-abf0-0b03d1e10190">

**Comment by chinmaypurav** [comment]
The issue which you are facing does not fall within the scope of this package.

This should help you with some debugging

https://spatie.be/docs/laravel-permission/v6/basic-usage/enums

Also I do have a small request; can you please paste you code in code blocks instead of an image? If someone has to try/test out the code, it will really be easy to copy paste the code block.

Thanks!

**Comment by kamaludin21** [comment]
thank's you give me clue, should rename from "SUPER ADMIN" to "SUPERADMIN. cannot use space 😄😄
